# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-mender-artifact-motd"
BBFILE_PATTERN_meta-mender-artifact-motd = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-mender-artifact-motd = "6"

LAYERDEPENDS_meta-mender-artifact-motd = "core"
LAYERSERIES_COMPAT_meta-mender-artifact-motd = "wrynose"
