# meta-mender-isar: Mender A/B (efibootmgr) integration for ISAR-built Debian.
BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "mender-isar"
BBFILE_PATTERN_mender-isar = "^${LAYERDIR_RE}/"
BBFILE_PRIORITY_mender-isar = "6"

LAYERVERSION_mender-isar = "1"
LAYERSERIES_COMPAT_mender-isar = "v0.6"

LAYERDIR_mender-isar = "${LAYERDIR}"
LAYERDIR_mender-isar[vardepvalue] = "meta-mender-isar"
